--- #YAML:1.0
name:                Win32-VisualStyles
version:             0.01
abstract:            Apply Win32 Visual (aka XP) Styles to windows
license:             ~
author:              
    - Robert May <robertmay@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
